// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Leaks {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::MonoMac.AppKit.NSTableView __mt_callStackTableView;
		
		private global::MonoMac.AppKit.NSTableView __mt_leaksTableView;
		
		private global::MonoMac.AppKit.NSButton __mt_logButton;
		
		private global::MonoMac.AppKit.NSTextField __mt_logNumber;
		
		private global::MonoMac.AppKit.NSTextField __mt_monoOutput;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("copyCallStack:")]
		partial void copyCallStack (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("process:")]
		partial void process (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("readAddresses:")]
		partial void readAddresses (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("readLog:")]
		partial void readLog (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Connect("callStackTableView")]
		private global::MonoMac.AppKit.NSTableView callStackTableView {
			get {
				this.__mt_callStackTableView = ((global::MonoMac.AppKit.NSTableView)(this.GetNativeField("callStackTableView")));
				return this.__mt_callStackTableView;
			}
			set {
				this.__mt_callStackTableView = value;
				this.SetNativeField("callStackTableView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("leaksTableView")]
		private global::MonoMac.AppKit.NSTableView leaksTableView {
			get {
				this.__mt_leaksTableView = ((global::MonoMac.AppKit.NSTableView)(this.GetNativeField("leaksTableView")));
				return this.__mt_leaksTableView;
			}
			set {
				this.__mt_leaksTableView = value;
				this.SetNativeField("leaksTableView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("logButton")]
		private global::MonoMac.AppKit.NSButton logButton {
			get {
				this.__mt_logButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("logButton")));
				return this.__mt_logButton;
			}
			set {
				this.__mt_logButton = value;
				this.SetNativeField("logButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("logNumber")]
		private global::MonoMac.AppKit.NSTextField logNumber {
			get {
				this.__mt_logNumber = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("logNumber")));
				return this.__mt_logNumber;
			}
			set {
				this.__mt_logNumber = value;
				this.SetNativeField("logNumber", value);
			}
		}
		
		[MonoMac.Foundation.Connect("monoOutput")]
		private global::MonoMac.AppKit.NSTextField monoOutput {
			get {
				this.__mt_monoOutput = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("monoOutput")));
				return this.__mt_monoOutput;
			}
			set {
				this.__mt_monoOutput = value;
				this.SetNativeField("monoOutput", value);
			}
		}
	}
}
